import React, {useEffect, useRef, useState} from 'react';
import {X, ArrowRight, RefreshCw} from 'lucide-react';
import {supabase} from './supabase';
import {statuses, managementTypes, statusLabel, responsibleId, canManage, filterLeads} from './commercial';
const stamp = value => new Intl.DateTimeFormat('es-PE',{dateStyle:'short',timeStyle:'short',timeZone:'America/Lima'}).format(new Date(value));
const day = value => value ? value.split('-').reverse().join('/') : 'Sin fecha';
export function StatusBadge({lead}) { return <span className={`status-badge status-${lead.commercial_status || 'nuevo'}`}>{statusLabel(lead.commercial_status)}</span>; }
export function Modal({title, onClose, children, small=false, busy=false}) {
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement; const scroll=document.body.style.overflow; document.body.style.overflow='hidden'; ref.current?.focus(); return ()=>{document.body.style.overflow=scroll; previous?.focus();};},[]);
 return <div className="commercial-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`commercial-dialog ${small?'compact':''}`} onKeyDown={e=>{
 if(e.key==='Escape'&&!busy){e.stopPropagation();onClose();}
 if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex="0"]')]; const first=nodes[0],last=nodes.at(-1); if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first?.focus();}}
 }}><div className="commercial-dialog-heading"><h2>{title}</h2><button className="icon-button" disabled={busy} aria-label="Cerrar" onClick={onClose}><X size={20}/></button></div>{children}</section></div>;
}
export function FollowupList({leads, profiles, loading, onOpen, onTransfer, onRefresh, user, profile}) {
 const [filters,setFilters]=useState({status:'',owner:'',company:'',registered:'',due:''});
 const visible=filterLeads(leads,filters);
 const change=(key,value)=>setFilters(f=>({...f,[key]:value}));
 return <><section className="page-heading"><div><span className="eyebrow">CADA CONVERSACIÓN, UN SIGUIENTE PASO</span><h1>Seguimiento</h1><p className="muted">Estado, última gestión y próximo paso de tus oportunidades.</p></div><button className="text-button" onClick={onRefresh} disabled={loading}><RefreshCw size={16}/> Actualizar</button></section>
 <div className="commercial-kpis" aria-label="Resumen comercial"><div><strong>{loading?'—':leads.length}</strong><span>Total de leads</span></div>{statuses.map(([key,,label])=><div key={key}><strong>{loading?'—':leads.filter(l=>(l.commercial_status||'nuevo')===key).length}</strong><span>{key==='cancelado'?'Cancelados / No aplica':label}</span></div>)}</div>
 <div className="commercial-chips" aria-label="Filtrar por estado">{[['','Todos'],...statuses.map(s=>[s[0],s[2]])].map(([key,label])=><button key={key} aria-pressed={filters.status===key} className={filters.status===key?'active':''} onClick={()=>change('status',key)}>{label}</button>)}</div>
 <div className="commercial-filters"><label>Responsable comercial<select value={filters.owner} onChange={e=>change('owner',e.target.value)}><option value="">Todos</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label>Empresa<input placeholder="Buscar empresa…" value={filters.company} onChange={e=>change('company',e.target.value)}/></label><label>Fecha de registro<input type="date" value={filters.registered} onChange={e=>change('registered',e.target.value)}/></label><label>Fecha próxima acción<input type="date" value={filters.due} onChange={e=>change('due',e.target.value)}/></label></div>
 <div className="commercial-result"><small aria-live="polite">{visible.length} leads · {profile?.role==='admin'?'Todo el equipo':'Registrados por ti o asignados a ti'}</small>{Object.values(filters).some(Boolean)&&<button className="text-button" onClick={()=>setFilters({status:'',owner:'',company:'',registered:'',due:''})}>Limpiar filtros</button>}</div>
 <section className="commercial-list">{loading?<p className="empty">Cargando seguimiento…</p>:visible.length?visible.map(l=><div className="commercial-row" key={l.id}><button className="commercial-row-main" onClick={()=>onOpen(l)}><span><strong>{l.empresa}</strong><small>{l.nombre}</small><StatusBadge lead={l}/></span><span><small>Responsable actual</small>{profiles.find(p=>p.id===responsibleId(l))?.full_name||l.profiles?.full_name||'—'}</span><span><small>Última gestión</small><span className="commercial-excerpt">{l.last_management||'Sin gestión comercial'}</span>{l.last_management_at&&<small>{stamp(l.last_management_at)}</small>}</span><span><small>Próxima acción</small>{l.next_action||'Por definir'}<small>{day(l.next_action_date)}</small></span><ArrowRight size={16}/></button>{canManage(l,user,profile)&&<button className="text-button transfer-inline" onClick={()=>onTransfer(l)}>Derivar</button>}</div>):<div className="empty"><h3>No hay leads que mostrar</h3><p>{leads.length?'Prueba con otros filtros.':'Los nuevos registros aparecerán aquí.'}</p></div>}</section></>;
}
export function CommercialDetail({lead, profiles, user, profile, demo, onClose, onUpdate, onTransfer}) {
 const [status,setStatus]=useState(lead.commercial_status||'nuevo'),[action,setAction]=useState(lead.next_action||''),[due,setDue]=useState(lead.next_action_date||''),[comment,setComment]=useState(''),[type,setType]=useState(''),[events,setEvents]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[photo,setPhoto]=useState(lead.demoPhoto||'');
 const editable=canManage(lead,user,profile);
 useEffect(()=>{setStatus(lead.commercial_status||'nuevo');setAction(lead.next_action||'');setDue(lead.next_action_date||'');},[lead.commercial_version]);
 useEffect(()=>{let active=true; (async()=>{setLoading(true);setError('');if(demo){setEvents(lead.events||[{id:'created',created_at:lead.created_at,actor_name:lead.profiles?.full_name,body:'Lead registrado.',kind:'created'}]);setLoading(false);return;}
 let all=[]; for(let from=0;;from+=1000){const {data,error}=await supabase.from('lead_events').select('*').eq('lead_id',lead.id).order('created_at',{ascending:false}).order('id').range(from,from+999);if(!active)return;if(error){setError('No se pudo cargar la bitácora. '+error.message);setLoading(false);return;}all.push(...data);if(data.length<1000)break;}setEvents(all);setLoading(false);})();return ()=>{active=false;};},[lead.id,lead.commercial_version,demo]);
 useEffect(()=>{let active=true;if(lead.photo_path&&!demo)supabase.storage.from('lead-photos').createSignedUrl(lead.photo_path,600).then(({data,error})=>{if(active){if(error)setError('No se pudo cargar la foto.');else setPhoto(data.signedUrl);}});return()=>{active=false;};},[lead.id]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{await onUpdate(lead,{status,next_action:action.trim(),next_action_date:due,comment:comment.trim(),management_type:type});setComment('');setType('');setNotice('Actualización registrada.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const changed=status!==(lead.commercial_status||'nuevo')||action.trim()!==(lead.next_action||'')||due!==(lead.next_action_date||'')||comment.trim();
 return <Modal title={lead.empresa} onClose={onClose} busy={busy}><p className="muted">{lead.nombre}</p><section className="commercial-section"><h3>Datos del lead</h3><dl className="commercial-data">{[['Empresa',lead.empresa],['Contacto',lead.nombre],['Cargo',lead.cargo],['Teléfono',lead.celular],['Correo',lead.correo],['DNI',lead.dni],['Registrado por',lead.profiles?.full_name],['Fecha de registro',stamp(lead.created_at)],['Rubro',lead.rubro],['Producto',lead.producto],['Detalle del producto',lead.producto_detalle],['Proyecto',lead.proyecto],['Fecha requerida',day(lead.fecha_necesita)],['Información captada en feria',lead.comentario]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl>{photo&&<img className="detail-photo" src={photo} alt="Foto captada en feria"/>}</section>
 <form onSubmit={save}><fieldset disabled={busy||!editable} className="commercial-section"><legend>Gestión comercial</legend><div className="commercial-result"><div><small>Responsable actual</small><p>{profiles.find(p=>p.id===responsibleId(lead))?.full_name||lead.profiles?.full_name}</p></div>{editable&&<button type="button" className="text-button" onClick={()=>onTransfer(lead)}>Derivar</button>}</div><p className="muted commercial-last">Última gestión: {lead.last_management||'Sin gestión comercial'}{lead.last_management_at&&` · ${stamp(lead.last_management_at)}`}</p><label>Cambiar estado<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p className="commercial-help">{statuses.find(s=>s[0]===status)?.[3]}</p><div className="grid"><label>Próxima acción<input maxLength={500} list="next-actions" placeholder="Por ejemplo, coordinar visita" value={action} onChange={e=>setAction(e.target.value)} required={!!due}/><datalist id="next-actions">{['Volver a llamar','Enviar información técnica','Agendar reunión','Coordinar visita','Solicitar planos','Elaborar presupuesto','Enviar propuesta'].map(a=><option key={a} value={a}/>)}</datalist></label><label>Fecha próxima acción<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div></fieldset>
 <section className="commercial-section"><h3>Comentarios / Bitácora</h3>{editable&&<fieldset disabled={busy} className="commercial-compose"><label><span className="commercial-help">Registrar seguimiento</span><textarea aria-label="Agregar comentario" placeholder="Agregar comentario…" maxLength={4000} required={!!type} value={comment} onChange={e=>setComment(e.target.value)}/></label><div className="commercial-chips" aria-label="Tipo de gestión">{managementTypes.map(t=><button type="button" key={t} aria-pressed={type===t} className={type===t?'active':''} onClick={()=>setType(type===t?'':t)}>{t}</button>)}</div><button className="primary" disabled={busy||!changed}>{busy?'Guardando…':'Registrar actualización'}</button></fieldset>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 {loading?<p className="muted">Cargando bitácora…</p>:<ol className="commercial-timeline">{events.map(event=><li key={event.id}><small>{stamp(event.created_at)} · {event.actor_name}</small>{event.management_type&&<span className="commercial-event-type">{event.management_type}</span>}<p>{event.body}</p>{event.new_status&&<p className="commercial-status-change">Estado actualizado: {statusLabel(event.old_status)} → {statusLabel(event.new_status)}</p>}</li>)}</ol>}</section></form></Modal>;
}
export function TransferModal({lead,profiles,onClose,onUpdate}) {
 const [target,setTarget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await onUpdate(lead,{responsible_id:target});onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal title="Derivar lead" small onClose={onClose} busy={busy}><p className="muted">{lead.empresa} · {lead.nombre}</p><p className="commercial-help">Responsable actual: {profiles.find(p=>p.id===responsibleId(lead))?.full_name||lead.profiles?.full_name}. La derivación conserva el estado y el registro original.</p><form onSubmit={save}><label>Nuevo responsable<select required disabled={busy} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Selecciona un comercial…</option>{profiles.filter(p=>p.id!==responsibleId(lead)).map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<div className="commercial-result"><button type="button" className="text-button" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy||!target}>{busy?'Derivando…':'Derivar'}</button></div></form></Modal>;
}
